service: decryptScrapper

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'tst'}
  region: us-east-1
  memorySize: 1024
  timeout: 800

plugins:
  - serverless-offline
  
functions:
  fetchArticles:
    handler: index.handler
    environment:
      STAGE: ${self:provider.stage}
    events:
      - http:
          path: /fetch-articles
          method: get
          cors: true
